### ISSUE TITLE
Allocation api returns 500 for some tickers

### ISSUE THREAD

**Issue by ricktjwong** [ricktjwong/alpha#32]
For example, the `AIO` ticker, if chosen, throws the error in the DB:
`sqlalchemy.orm.exc.NoResultFound: No row was found for one()`

**Comment by ng95junwei** [comment]
This bug happens because the ticker data is populated before the historical data. As a result, the tickers which can't be found on yfinance or those with <1 year of data will show this error. 

We can probably get around this by:
1. Changing how the seeding is done (Seed ohlc, then seed tickers using ohlc distinct symbols)
2. Use OHLC Table to return ticker symbols instead.
